export default function About() {
  return (
    <>
      <div>
      <p>
        an online marketing, a landing page, sometimes known as a "lead capture
        page", "single property page", "static page", "squeeze page" or a
        "destination page", is a single web page that appears in response to
        clicking on a search engine optimized search result, marketing
        promotion, marketing email or an online advertisement.[1] The landing
        page will usually display directed sales copy that is a logical
        extension of the advertisement, search result or link. Landing pages are
        used for lead generation. The actions that a visitor takes on a landing
        page are what determine an advertiser's conversion rate. A landing page
        may be part of a microsite or a single page within an organization's
        main web site. Landing pages are often linked to social media, e-mail
        campaigns, search engine marketing campaigns, high-quality articles or
        "affiliate account" in order to enhance the effectiveness of the
        advertisements. The general goal of a landing page is to convert site
        visitors into sales or leads. If the goal is to obtain a lead, the
        landing page will include some method for the visitor to get into
        contact with the company, usually a phone number or an inquiry form. If
        a sale is required, the landing page will usually have a link for the
        visitor to click, which will then send them to a shopping cart or as
        checkout area. By analyzing activity generated by the linked URL,
        marketers can use click-through rates and conversion rate to determine
        the success of an advertisement.[2


        hi it is working daa  



        
      </p>
    </div>

    <div>
      <h1>namma tha eppayme namma daaa</h1>
    </div>
    </>
  );
}
